import React, { useMemo } from "react";
import { ScrollView, View, Text, StyleSheet } from "react-native";
import { C, starString } from "../theme.js";
import { generateSquad, POSITION_NAMES, fmtK } from "../engine.js";

export default function RecruitScreen({ career }) {
  const { club, tier, season } = career;
  const [c1] = club.colors || [C.sky];

  // Available pool generated by the shared engine (a separate seed → new faces).
  const pool = useMemo(
    () =>
      generateSquad("pool", tier, 16, season + 1)
        .slice()
        .sort((a, b) => b.overall - a.overall),
    [tier, season],
  );

  return (
    <ScrollView style={{ flex: 1, backgroundColor: C.bg }} contentContainerStyle={{ paddingBottom: 28 }}>
      <View style={[styles.stripe, { backgroundColor: c1 }]} />
      <View style={styles.header}>
        <Text style={styles.kicker}>RECRUIT · TRADE MARKET</Text>
        <Text style={styles.h1}>AVAILABLE</Text>
        <Text style={styles.sub}>{pool.length} players across the pyramid · ask price shown</Text>
      </View>

      <View style={styles.legend}>
        <Text style={[styles.lh, { flex: 1 }]}>PLAYER</Text>
        <Text style={[styles.lh, { width: 42, textAlign: "center" }]}>AGE</Text>
        <Text style={[styles.lh, { width: 78, textAlign: "right" }]}>RATING</Text>
        <Text style={[styles.lh, { width: 70, textAlign: "right" }]}>ASK</Text>
      </View>

      <View style={{ paddingHorizontal: 18 }}>
        {pool.map((p, i) => (
          <View key={p.id ?? i} style={styles.row}>
            <View style={{ flex: 1 }}>
              <Text style={styles.name}>{p.firstName} {p.lastName}</Text>
              <Text style={styles.posName}>{POSITION_NAMES?.[p.position] || p.position}</Text>
            </View>
            <Text style={styles.age}>{p.age}</Text>
            <Text style={styles.stars}>{starString(p.overall)}</Text>
            <Text style={styles.ask}>{fmtK(Math.round((p.wage || 0) * 1.4))}</Text>
          </View>
        ))}
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  stripe: { height: 4, width: "100%" },
  header: { paddingHorizontal: 18, paddingTop: 12, paddingBottom: 10 },
  kicker: { color: C.sky, fontSize: 11, fontWeight: "800", letterSpacing: 2 },
  h1: { color: C.text, fontSize: 26, fontWeight: "900", marginTop: 3, letterSpacing: -0.5 },
  sub: { color: C.mute, fontSize: 12, marginTop: 5 },
  legend: {
    flexDirection: "row", alignItems: "center", paddingHorizontal: 18, paddingVertical: 8,
    borderTopWidth: 1, borderBottomWidth: 1, borderColor: C.line,
  },
  lh: { color: C.mute, fontSize: 10, fontWeight: "800", letterSpacing: 1 },
  row: { flexDirection: "row", alignItems: "center", paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: C.line },
  name: { color: C.text, fontSize: 15, fontWeight: "700" },
  posName: { color: C.dim, fontSize: 11, marginTop: 1 },
  age: { color: C.mute, fontSize: 13, width: 42, textAlign: "center", fontVariant: ["tabular-nums"] },
  stars: { color: C.sky, fontSize: 12, width: 78, textAlign: "right", letterSpacing: 1 },
  ask: { color: C.gold, fontSize: 13, width: 70, textAlign: "right", fontWeight: "800", fontVariant: ["tabular-nums"] },
});
